#!/usr/bin/env python3
"""Generate ZMK physical-layout keys for NocFree & Studio UI.

96 keymap positions (left 0-47, right 48-95).

Right edge (user-confirmed physical geometry):
  r0: ... PrtSc | Home | Del     (Del is on r0 — matrix pos still 79)
  r1: ... Bksp  | PgUp
  r2: ... ] \\  | PgDn           (PgDn matrix pos 87 drawn here)
  r3: ... Enter                  (no Del here)
  r4: ... RSft  | Up
  r5: arrows

Left: two SPACE matrix positions → one physical bar.
"""
from __future__ import annotations

U = 100
GAP = 150
LEFT_N = [7, 7, 6, 6, 6, 6]
RIGHT_GHOST_BITS = {5: {7}}

LEFT_WIDE = {
    (2, 0): 150,  # Tab
    (3, 0): 175,  # Caps
    (4, 0): 225,  # LShift
    (5, 4): 250,  # single space (matrix 44+45)
}

RIGHT0 = 7 * U + GAP
EDGE_X = RIGHT0 + 6 * U  # PrtSc, Bksp, ], Enter, Up, ...
NAV_X = EDGE_X + U  # Home, PgUp, PgDn, ...
DEL_X = NAV_X + U  # Del on r0 only, right of Home


def attrs(w: int, h: int, x: int, y: int) -> str:
    return f"<&key_physical_attrs {w:3d} {h:3d} {x:4d} {y:4d} 0 0 0>"


def left_pos(row: int, bit: int) -> tuple[int, int, int] | None:
    if row == 5 and bit == 5:
        return None  # 2nd SPACE — parked; one bar at bit 4
    y = row * U
    x = 0
    for b in range(bit):
        if row == 5 and b == 5:
            continue
        x += LEFT_WIDE.get((row, b), U)
    w = LEFT_WIDE.get((row, bit), U)
    return w, x, y


def right_pos(row: int, bit: int) -> tuple[int, int, int]:
    y = row * U

    # r0: F7-F12 | PrtSc | Home | (Del drawn from matrix r3)
    if row == 0:
        if bit <= 5:
            return U, RIGHT0 + bit * U, y
        if bit == 6:
            return U, EDGE_X, y  # PrtSc
        return U, NAV_X, y  # Home

    # r1: 7-0-= | Bksp | PgUp
    if row == 1:
        if bit <= 5:
            return U, RIGHT0 + bit * U, y
        if bit == 6:
            return U, EDGE_X, y
        return U, NAV_X, y  # PgUp

    # r2: Y-P [ ] \ | PgDn
    if row == 2:
        if bit <= 4:
            return U, RIGHT0 + bit * U, y
        if bit == 5:
            return U, RIGHT0 + 5 * U, y  # [
        if bit == 6:
            return U, EDGE_X - U, y  # ]
        return U, EDGE_X, y  # \  (left of PgDn)

    # r3: H-' | Enter — Del matrix bit 7 is drawn on r0 at DEL_X
    if row == 3:
        if bit <= 5:
            return U, RIGHT0 + bit * U, y
        if bit == 6:
            return 150, EDGE_X - 50, y  # Enter
        # Del: physical r0, right of Home
        return U, DEL_X, 0

    # r4: N-/ RSft Up | PgDn matrix → r2 NAV
    if row == 4:
        if bit <= 4:
            return U, RIGHT0 + bit * U, y
        if bit == 5:
            return 150, RIGHT0 + 5 * U, y
        if bit == 6:
            return U, EDGE_X, y  # Up
        return U, NAV_X, 2 * U  # PgDn on r2 under PgUp, right of \

    # r5: space mods arrows
    if row == 5:
        if bit == 0:
            return 200, RIGHT0, y
        if bit == 1:
            return U, RIGHT0 + 200, y
        if bit == 2:
            return U, RIGHT0 + 300, y
        if bit == 3:
            return U, RIGHT0 + 400, y
        if bit == 4:
            return U, EDGE_X - U, y
        if bit == 5:
            return U, EDGE_X, y
        if bit == 6:
            return U, NAV_X, y

    return U, RIGHT0 + bit * U, y


def main() -> None:
    keys: list[str] = []
    ghost_i = 0
    for pos in range(96):
        if pos < 48:
            row, bit = divmod(pos, 8)
            if bit >= LEFT_N[row]:
                keys.append(attrs(50, 50, 3200 + ghost_i * 20, 0))
                ghost_i += 1
                continue
            lp = left_pos(row, bit)
            if lp is None:
                keys.append(attrs(50, 50, 3200 + ghost_i * 20, 0))
                ghost_i += 1
                continue
            w, x, y = lp
            keys.append(attrs(w, U, x, y))
        else:
            row, bit = divmod(pos - 48, 8)
            if bit in RIGHT_GHOST_BITS.get(row, set()):
                keys.append(attrs(50, 50, 3200 + ghost_i * 20, 0))
                ghost_i += 1
                continue
            w, x, y = right_pos(row, bit)
            keys.append(attrs(w, U, x, y))

    print("\t\t/* Generated by tools/gen_studio_layout.py */")
    print("\t\tkeys")
    for i, k in enumerate(keys):
        sep = "=" if i == 0 else ","
        print(f"\t\t\t{sep} {k}")
    print("\t\t\t;")


if __name__ == "__main__":
    main()
